// Single source of truth for every test. Gameplay modules attach to these ids later.
export const tests = [
  { id: 'memory', title: 'Memory Span', icon: '🧩', category: 'Memory', difficulty: 'Easy', minutes: 4, tone: 'indigo',
    summary: 'Watch a sequence of tiles light up, then repeat it. Sequences grow longer each round.',
    why: 'Working memory holds a few items in mind at once. It supports reasoning, reading and following directions.',
    steps: ['Watch the tiles light up in order.', 'Repeat the sequence by clicking the tiles.', 'Each correct round adds one more tile.'] },
  { id: 'short-term-memory', title: 'Short-Term Memory', icon: '📝', category: 'Memory', difficulty: 'Easy', minutes: 2, tone: 'teal',
    summary: 'Memorize six words for eight seconds, then pick them out from a longer list.',
    why: 'Short-term memory keeps information available for a few seconds. Without rehearsal it fades quickly.',
    steps: ['Study the six words before they disappear.', 'Select every word you remember.', 'Wrong picks reduce your score, so only pick words you saw.'] },
  { id: 'reaction-time', title: 'Reaction Time', icon: '⚡', category: 'Speed', difficulty: 'Easy', minutes: 2, tone: 'amber',
    summary: 'Click as fast as you can the moment the screen changes color.',
    why: 'Reaction time measures how quickly you detect a signal and act. Alertness and fatigue both affect it.',
    steps: ['Wait for the panel to turn green.', 'Click or press Space immediately.', 'Clicking too early counts as a false start.'] },
  { id: 'attention', title: 'Sustained Attention', icon: '🎯', category: 'Attention', difficulty: 'Medium', minutes: 5, tone: 'teal',
    summary: 'Spot rare targets in a stream of symbols without reacting to look-alikes.',
    why: 'Sustained attention is the ability to stay focused on a dull task. It drifts over time for everyone.',
    steps: ['Symbols appear one at a time.', 'Respond only when the target appears.', 'Ignore look-alikes.'] },
  { id: 'pattern-recognition', title: 'Pattern Recognition', icon: '🔷', category: 'Reasoning', difficulty: 'Medium', minutes: 5, tone: 'violet',
    summary: 'Find the rule behind a sequence of shapes and choose what comes next.',
    why: 'Spotting patterns is central to learning and problem solving. It is a core part of fluid reasoning.',
    steps: ['Study the sequence of shapes.', 'Work out the rule.', 'Pick the shape that completes it.'] },
  { id: 'stroop', title: 'Stroop Challenge', icon: '🎨', category: 'Focus', difficulty: 'Hard', minutes: 3, tone: 'rose',
    summary: 'Name the ink color of a word, even when the word spells a different color.',
    why: 'Reading is automatic, so a conflicting word slows you down. This shows how your brain handles interference.',
    steps: ['A color word appears in colored ink.', 'Choose the ink color, not the word.', 'Answer quickly and accurately.'] },
  { id: 'decision-making', title: 'Decision Scenarios', icon: '⚖️', category: 'Judgment', difficulty: 'Medium', minutes: 6, tone: 'slate',
    summary: 'Choose between realistic options and see what your choices say about your decision style.',
    why: 'There are no right answers here. The results describe tendencies such as risk tolerance and speed.',
    steps: ['Read each short scenario.', 'Pick the option you would choose.', 'Go with your instinct.'] },
];
export const getTest = (id) => tests.find((t) => t.id === id);
